config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
	path('', views.HomePageView.as_view(), name='home'),
	path('profile/', views.DashboardView.as_view(), name='dashboard'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):

	def __str__(self):
		return self.email

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
	class Meta:
		model = CustomUser
		fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):
	class Meta:
		model = CustomUser
		fields = ('username', 'email')

accounts/views.py
from django.shortcuts import render

pages/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View


class HomePageView(View):
	def get(self, request):
		messages.success(request, "Homepage")
		return render(request, 'pages/home.html')


class DashboardView(LoginRequiredMixin, View):
	def get(self, request):
		return render(request, 'pages/dashboard.html')

templates/_menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-custom">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'pages:home' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'pages:dashboard' %}">Profile</a>
                    </li>
                {% endif %}
            </ul>
        </div>

        <div class="collapse navbar-collapse navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            {{ user.email }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a></li>
                            <li><a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a>
                            </li>
{#                            <li>#}
{#                                <hr class="dropdown-divider">#}
{#                            </li>#}
{#                            <li><a class="dropdown-item" href="#">Something else here</a></li>#}
                        </ul>
                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'account_login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'account_signup' %}">Sign Up</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

templates/_messages.html
{% if messages %}
    <div id="msg-content">
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% else %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}
    </div>

        <script>
            const msgContainer = document.querySelector("#msg-container")
            setTimeout(() => msgContainer.innerHTML = "", 3000)
        </script>

{% endif %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block links %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
              crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Ubuntu:300,400,600,700&amp;lang=en"/>
    {% endblock links %}

    <title>
        {% block title %}
        {% endblock title %}
    </title>

</head>

<body>

{% block menu %}
    {% include '_menu.html' %}
{% endblock menu %}


{% block messages %}
    <div class="position-absolute text-center justify-content-center" id="msg-container">
        {% include '_messages.html' %}
    </div>
    <div></div>
{% endblock messages %}

<div class="container mt-5">
    {% block content %}
    {% endblock content %}
</div>


{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>
{% endblock scripts %}

</body>

</html>

templates/pages/dashboard.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
  <div class="mt-5">
    Dashboard.
  </div>
{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
  <div class="mt-5">
    Homepage.
  </div>
{% endblock content %}